### ISSUE TITLE
Nativescript 8

### ISSUE THREAD

**Issue by rubenhr** [kefahB/nativescript-google-maps#1]
Is this working for Nativescript 8.
I have checked out and try to use your plugin and it works on iOS, but Android still not able to make it work. The map, doesn't show up
<img width="908" alt="Screen Shot 2022-01-10 at 10 16 00" src="https://user-images.githubusercontent.com/5392110/148799736-76c2f4de-3d5b-4d9d-9602-f39104ee8c8a.png">
.

**Comment by kefahB** [comment]
Hi,

You can try the last version I've published just right now.. it was a strange little issue.

**Comment by rubenhr** [comment]
Thanks for fast response.

**Comment by rubenhr** [comment]
Hi, isn't working yet. Android is throwing an error: 
<img width="973" alt="Screen Shot 2022-01-10 at 15 21 16" src="https://user-images.githubusercontent.com/5392110/148841341-7ce5fcba-203a-4b44-9467-9a7c293d434a.png">

**Comment by kefahB** [comment]
The new Renderer has a bunch of little issus, This issu that you have its is about the new Renderer of android, please dont forged to clean your app once you updated the plugin because the `LATEST` property work as expected

Can you past here info about you Nativescript environment and which android device and API do you use currently

**Comment by kefahB** [comment]
Do you have this into your `app.gradle` :

```ts
project.ext {
        googlePlayServicesVersion = "+"
    }
```

The new renderer it work from the versio `18.0.0`of the googlePlayServices

if this does not work try to edit the `googlePlayServicesVersion = "18.0.0"` and clean then run

**Comment by rubenhr** [comment]
Hi, I made the changes you suggest but I'm still getting the same error. Off course I clean all environment and run again.

Testing on Samsung Note 10+ on android version: 11

Here is my setup. Running NS 8.1.5
Android: 8.1.1
iOS: 8.1.0

Angular: 12.2.5

![Screen Shot 2022-01-11 at 09 08 20](https://user-images.githubusercontent.com/5392110/148968043-499fea54-b433-4644-b785-23cb90881bad.png)
![Screen Shot 2022-01-11 at 09 08 42](https://user-images.githubusercontent.com/5392110/148968218-ba6e93a8-dfef-479a-ace1-0b217cb0168a.png)

**Comment by kefahB** [comment]
Please can you make a little project to inspect your code .. beacuse I was not able to reproduce you case even on Samsung Note 10+ on android version: 11

**Comment by kefahB** [comment]
Hi,

Please clone this [this plugin demo](https://github.com/kefahB/packages) and go to `tools/assets/App_Resources/Android/src/main/res/values/nativescript_google_maps_api.xml` and change `Your_KEY` by your real google maps key.

Then run `npm start` and choose  `apps.demo-angular.android` for Angular or select  others...

**Comment by kefahB** [comment]
Hi @rubenhr,

do you resolve your issu ? If it is the case please close this because I would like to keep this repo clean 🙂

**Comment by rubenhr** [comment]
Hi, yes, I was able to figure out the issue. Looks like we have some configuration information in our app.gradle file that was not needed. So we clean that and start working. Closing this because is working as expected.

**Comment by SingleMalted** [comment]
@rubenhr I'm having the same issue. What config info did you remove to alleviate this issue?

Thanks
