### ISSUE TITLE
{N} 8.1 iOS app crashes immediately attempting to navigate to map page

### ISSUE THREAD

**Issue by dlcole** [kefahB/nativescript-google-maps#2]
I'm working with your plugin as I migrate a large JavaScript project from {N} 6.8 to 8.1.  First, I appreciate you creating this fork, as Google Maps are a key part of my app.  I'm starting on iOS, and I've made these changes so far in my map-page.xml file: 

```
- xmlns:maps="nativescript-google-maps-sdk"  
+ xmlns:maps="@kefah/nativescript-google-maps"
```
and
```
- maps:mapView id="locmap" latitude="{{ latitude }}" longitude="{{ longitude }}"
+ maps:GoogleMaps id="locmap" latitude="{{ latitude }}" longitude="{{ longitude }}" 
```

The app crashes immediately without any thrown errors when navigating to that page, with the navigatingTo event never firing.  Is there more that's required here?  Here's the complete, stripped-down version of the xml file: 

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd"
  xmlns:maps="@kefah/nativescript-google-maps"
  navigatingTo="onNavigatingTo" navigatingFrom="onNavigatingFrom" loaded="onLoaded" class="page">
  <Page.actionBar>
    <ActionBar title="{{ tappedItem.title }}" class="action-bar">
      <NavigationButton text="Back" android.systemIcon="ic_menu_back" tap="{{backTap}}"/>
    </ActionBar>
  </Page.actionBar>
  <GridLayout >
    <maps:GoogleMaps id="locmap" latitude="{{ latitude }}" longitude="{{ longitude }}" zoom="{{ zoom }}" mapReady="onMapReady" />
  </GridLayout>
</Page>
```

I'll be happy to update the readme file if appropriate.

**Comment by kefahB** [comment]
Hi,

Can you tel me about your environment please ?

The Maps it installed on tow production app and it work as expected, just a small issu with the infowindow but on android

Thanks

**Comment by dlcole** [comment]
@kefahB I'll prepare a small sample app with just a map to demo the problem.  Thanks for your quick response!

**Comment by kefahB** [comment]
if you use  `mapView.myLocationEnabled = true` please declare those at your info.plist


```xml
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>Your MSG</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>Your MSG</string>
```

**Comment by dlcole** [comment]
@kefahB Here's a very simple demo project:  [https://github.com/dlcole/maptester](https://github.com/dlcole/maptester)

This is a {N} 8.1 JavaScript project.  I was running on an iOS emulator, iOS 13.2, iPhone 11 Pro.  I have not attempted anything on Android yet.  Thanks for any help you can offer!

**Comment by kefahB** [comment]
Hi,

I was able to reproduce the error and get the maps work.


You have 2 small error .. on this sample demo :

at `app.js` you should declare the `GMSServices` like this and change `_YOUR_KEY_`by tour google maps key

```ts
import { Application } from '@nativescript/core';

if(Application.ios) {
  GMSServices.provideAPIKey("_YOUR_KEY_");
}

Application.run({ moduleName: 'app-root' })
```

at `map-page.js` you forged a let viewmodel : 
```ts
export function onNavigatingTo(args) {
  const page = args.object;
  let viewModel = page.navigationContext.bindingContext;
  page.bindingContext = viewModel;
}   

```

**Comment by dlcole** [comment]
@kefahB - yep, I have those in the actual app, I was just going with a fresh Hello World project and neglected to add those.  I'll make those changes and see if that works.  Thanks!

**Comment by dlcole** [comment]
With those two changes I am successfully able to display an empty map.  So, that much is good.  I'll go ahead and close this issue.  Thanks again for the prompt replies!

**Comment by dlcole** [comment]
I do have this warning when I build the sample project: 

```
WARNING in ./node_modules/@kefah/nativescript-google-maps/common.js 73:0-30
export 'Style' (reexported as 'StyleBase') was not found in './index' (possible exports: Bounds, Circle, GoogleMaps, Marker, Polygon, Polyline, Position, Projection, UISettings, VisibleRegion)
 @ ./node_modules/@kefah/nativescript-google-maps/index.ios.js 1:0-267 70:16-50 74:16-51 78:16-49 82:16-46 86:16-46 89:40-75 102:32-64 114:38-76 121:38-79 299:32-48 464:32-46 538:32-46 563:35-52 592:28-38 613:30-42 643:28-38 707:16-27 773:30-42 830:29-40 903:28-38
 @ ./app/map-page.xml 3:7-129 7:7-129
 @ ./app/ sync .(xml|js|s?css)$ ./map-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_javascript__ 3:16-89
```

It's just a warning, but would be nice to correct.

**Comment by kefahB** [comment]
This is already handled by the upcoming version
