### ISSUE TITLE
Could not find com.android.tools.build:gradle:4.5.6.

### ISSUE THREAD

**Issue by rubenhr** [kefahB/nativescript-google-maps#5]
Starting yesteday. Some weird behavior start ocurring. We didn't change anything in terms of configurations but our builds stops working.

Do you know, what could be a reason this starts failing?

<img width="1141" alt="Screen Shot 2022-03-08 at 09 05 34" src="https://user-images.githubusercontent.com/5392110/157265469-00bf45da-aea5-4d96-9d0d-4aacd9b1f1d0.png">

**Comment by kefahB** [comment]
Hi,

Do you have this in your  `/app/App_Resources/Android/app.gradle` ?

```ts
project.ext {
    googlePlayServicesVersion = "+"
}
```

**Comment by kefahB** [comment]
If it doesn't work, please post info about your NS config `ns info` and with which version on android you'r running.

**Comment by ebiscardi** [comment]
I have the same issue. Just to try to identify the problem, should be this issue related to the use of _compile_ instruction in include.gradle, removed in gradle 7?
https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal

As described here:
https://github.com/NativeScript/android-runtime/issues/1706
when Nativescript CLI builds on Android, Gradle version is not pulled from the current platform, but from the latest Nativescript version, using first

`npm view @nativescript/android  dist-tags --json`

to get the latest version, and then 

`npm view @nativescript/android@<version> gradle --json`

to get the appropriate gradle info

You can see that using `--log trace ` option when you build on Android.
For this reason, version 8.2.0 is broken, and fails to build on Android
The latest version (8.2.1), released some hours later, uses gradle 7.4:

```
npm view @nativescript/android@8.2.1  gradle --json
{
  "version": "7.4",
  "android": "7.1.2"
}
```

the previous ones, version 6.4

```
npm view @nativescript/android@7.0.1  gradle --json
{
  "version": "6.4",
  "android": "3.6.4"
}

npm view @nativescript/android@8.1.1  gradle --json
{
  "version": "6.4",
  "android": "3.6.4"
}
```

**Comment by rubenhr** [comment]
HI @kefahB 
Yes, I have the googlePlayServicesVersion = "+" in our app.gradle file.
Weird thing is that suddently, everything starts working fine. But today I'm getting the same issue again.

We are using 8.1.5 version with Android 8.1.1.

But for some reason, gradle picks up latest version instead of the appropiate.

**Comment by lambourn** [comment]
see https://github.com/NativeScript/NativeScript/issues/9814#issuecomment-1062928925 - that should fix the issue (needs you to update CLI, though)

**Comment by kefahB** [comment]
Thanks @lambourn ;)

@rubenhr please try the fix and tel me

**Comment by CalebSWhite** [comment]
@kefahB Might need to update the [include.gradle](https://github.com/kefahB/nativescript-google-maps/blob/main/platforms/android/include.gradle#L8) to use `implementation` rather than the deprecated `compile`.

**Comment by kefahB** [comment]
Hi everyone,

I've published a new version .. please give it a try and tel me if every think run as expected

**Comment by rubenhr** [comment]
Hi everyone.

So, at the end, I was able to fix all my issues upgrading to new NS version and also upgrading NG version.
I'm running now on 8.2.2 with Java 11.

I'm getting this error right now:

<img width="1800" alt="Screen Shot 2022-03-10 at 12 18 32" src="https://user-images.githubusercontent.com/5392110/157728941-0d109562-ddb2-4092-a1b9-ea46dc690280.png">

**Comment by lekhmanrus** [comment]
I have the same error as @rubenhr has:
```
ERROR in ./node_modules/@kefah/nativescript-google-maps/index.android.ts
Module build failed (from ../../node_modules/@ngtools/webpack/src/index.js):
Error: \node_modules\@kefah\nativescript-google-maps\index.android.ts is missing from the TypeScript 
compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at \node_modules\@ngtools\webpack\src\ivy\loader.js:60:26
```

@nativescript/android: **8.2.2**
@kefah/nativescript-google-maps: **1.0.4**

**Comment by kefahB** [comment]
@lekhmanrus, @rubenhr can you provide a sample project with the error, because every think work as expected even with angular project.

**Comment by CalebSWhite** [comment]
@kefahB looks like you might have published the plugin unbuilt to npm. It doesn't have the js files and it shouldn't include the tsconfig

**Comment by kefahB** [comment]
@calebswhite, I've build the project, in my own I do have the tsconfig ! and it work as expected!

**Comment by CalebSWhite** [comment]
It just looks a bit different from the previous (npm) packaged version. Since no code was changed (just the gradle and a version bump) I assumed it was a build/packing step???
![image](https://user-images.githubusercontent.com/30383889/157841878-df30809c-277d-44a0-b920-94930ff98b71.png)

**Comment by kefahB** [comment]
Oh, I've mad a npm publish that does not build by default! this repo it is a NS plugin that integrate the command npm run publish-package and it does the build before pushing a new version :)

Please take a test and tel me ;)

**Comment by CalebSWhite** [comment]
Good stuff. v1.0.6 is working for me.

**Comment by rubenhr** [comment]
1.0.6 is working for me too. We can close this ticket. Thanks a lot for all comments
