### ISSUE TITLE
StyleBase circular export Android

### ISSUE THREAD

**Issue by SingleMalted** [kefahB/nativescript-google-maps#8]
@kefahB I'm seeing this error during my project build (Android). I see a @ts-ignore in common.ts... could that export be causing the problem?
https://github.com/kefahB/nativescript-google-maps/blob/c9c5e8c573fe978476c9c99c42a2ed34b0ba8a6f/common.ts#L89 https://github.com/kefahB/nativescript-google-maps/blob/c9c5e8c573fe978476c9c99c42a2ed34b0ba8a6f/common.ts#L90

> `ERROR in chunk vendor [initial]
> vendor.js
> /bitrise/src/node_modules/@kefah/nativescript-google-maps/index.js 2a9c7e95dc08d68bf21e9190814023a8
> Circular reexports "../node_modules/@kefah/nativescript-google-maps/index.js".StyleBase --> "../node_modules/@kefah/nativescript-google-maps/common.js".StyleBase -(circular)-> "../node_modules/@kefah/nativescript-google-maps/index.js".StyleBase`

**Comment by kefahB** [comment]
Hi,

Please see [here](https://github.com/dapriett/nativescript-google-maps-sdk/issues/455#issuecomment-1059136306) if will help!

**Comment by SingleMalted** [comment]
Thanks @kefahB I thought for sure that would fix my error but it didn't help.

**Comment by kefahB** [comment]
Hi @SingleMalted, could you try the fixed version please, I've pushed just now

**Comment by SingleMalted** [comment]
@kefahB the issue is now resolved. Thanks for the quick fix.

Cheers
